In [40]:
import itertools as it
import functools as ft
import toolz as tz
import numpy as np

In [1]:
numbers = list(range(1, 11))

In [2]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Map

In [3]:
numbers2 = list(map(lambda n: n + 2, numbers))

In [4]:
numbers2

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Filter

In [5]:
list(filter(lambda n: n < 5, numbers))

[1, 2, 3, 4]

In [10]:
[n * 2 for n in numbers if (n < 7) and (n * 2 >= 9)]

[10, 12]

In [11]:
def summator(a):
    def inner_summator(b):
        return a + b
    return inner_summator

In [12]:
add5 = summator(5)

In [13]:
[add5(n) for n in numbers]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [15]:
add10 = summator(10)

In [16]:
[add5(n) + add10(n) for n in numbers]

[17, 19, 21, 23, 25, 27, 29, 31, 33, 35]

In [23]:
list(it.filterfalse(lambda x: x%2, range(20)))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [24]:
list(it.accumulate([1,2,3,4,5]))

[1, 3, 6, 10, 15]

In [27]:
ft.cache
def factorial(n):
    return n * factorial(n-1) if n else 1

In [38]:
def partial(func, /, *args, **keywords):
    def newfunc(*fargs, **fkeywords):
        newkeywords = {**keywords, **fkeywords}
        return func(*args, *fargs, **newkeywords)
    newfunc.func = func
    newfunc.args = args
    newfunc.keywords = keywords
    return newfunc

In [41]:
np.arange(20) + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [42]:
np.arange(20) > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [43]:
np_nums = np.arange(20)
np_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
list(np_nums[np_nums > 3] * 2)

[8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [50]:
np_nums * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57])